### ISSUE TITLE
Unrecognized function or variable 'lobpcg'

### ISSUE THREAD

**Issue by adthoms** [MarineRoboticsGroup/cora-matlab#4]
@alanpapalia [lobpcg](https://github.com/lobpcg/blopex/blob/master/blopex_tools/matlab/lobpcg/lobpcg.m) should be included in cora/MATLAB/utils/math_utils (or another suitable location). Let me know if you would like to address this, I want to make sure the function file is included in the proper place.

**Comment by alanpapalia** [comment]
I've been installing from [MATLAB file exchange](https://www.mathworks.com/matlabcentral/fileexchange/48-locally-optimal-block-preconditioned-conjugate-gradient) via the Add-On Explorer - hence reason why I haven't added the file to the repo directly. I assumed that this would be a little easier for individuals and reduce how much code we have to think about.

If you migrate the file(s) over and in tests it seems like runtime & integration are equivalent then I'm happy to merge this in.
